name: InsightPix DB Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Copy .env.example → .env
        run: cp .env.example .env

      - name: Build and start DB
        run: docker compose up -d --build

      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..15}; do
            if docker compose exec db pg_isready -U $POSTGRES_USER -d $POSTGRES_DB; then
              echo "✅ PostgreSQL is ready"
              break
            fi
            echo "⏳ Waiting for PostgreSQL..."
            sleep 3
          done

      - name: Run pgTAP tests
        run: docker compose exec db sh /scripts/test.sh

      - name: Stop containers
        if: always()
        run: docker compose down -v
